version: "3.8"

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"

  service-a:
    build:
      context: ./service_a
      dockerfile: Dockerfile
    env_file:
      - ./service_a/cmd/.env
    ports:
      - "8080:8080"
    depends_on:
      - service-b
      - otel-collector
      - zipkin

  service-b:
    build:
      context: ./service_b
      dockerfile: Dockerfile
    env_file:
      - ./service_b/cmd/.env
    ports:
      - "8081:8080"
    depends_on:
      - otel-collector
      - zipkin
